/*
 * snoopfs.c
 * Do not edit by hand.
 * Automatically generated by fistgen.
 */

#ifdef HAVE_CONFIG_H
# include <config.h>
#endif /* HAVE_CONFIG_H */
#ifdef FISTGEN
# include "fist_snoopfs.h"
#endif /* FISTGEN */
#include "fist.h"
#include "snoopfs.h"

/* OPTIONAL CODE FOLLOWS */

/* no extra routines are needed */

/*
 * Local variables:
 * c-basic-offset: 4
 * End:
 */


uid_t
fist_getattr_owner(vnode_t *vp, cred_t *cr)
{
  vattr_t va;
  int err;

  VATTR_NULL(&va);
  err = VOP_GETATTR(vp, &va, cr, curthread);
  if (err)
    return -1;
  return va.va_uid;
}

